"""create_shows_table

Revision ID: ffc73bb596a4
Revises: b912e66371ed
Create Date: 2026-04-11 19:18:57.141962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc73bb596a4'
down_revision: Union[str, Sequence[str], None] = 'b912e66371ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('show_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    op.create_index(op.f('ix_shows_movie_id'), 'shows', ['movie_id'], unique=False)
    op.create_index(op.f('ix_shows_show_time'), 'shows', ['show_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_show_time'), table_name='shows')
    op.drop_index(op.f('ix_shows_movie_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
